#!/usr/bin/with-contenv sh

#run the default config script
sh /srv/config.sh

#chown the mopidy directory by the new user
chown mediadepot:mediadepot -R /srv/mopidy

# run mopidy
HOME=/home/mediadepot
exec s6-setuidgid mediadepot mopidy --config /srv/mopidy/config/mopidy.conf
